### ISSUE TITLE
동작하지 않음

### ISSUE THREAD

**Issue by nonbanana** [mbin96/youtube_ass_subtitle#20]
```
subtitles-octopus.js:71 Worker error:  Don't know where to render: you should give video or canvas in options.
SubtitlesOctopus.self.workerError @ subtitles-octopus.js:71
subtitles-octopus.js:77 Uncaught (in promise) Error: Worker error: Don't know where to render: you should give video or canvas in options.
    at SubtitlesOctopus.self.workerError (chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/subtitles_octopus/subtitles-octopus.js:77:19)
    at SubtitlesOctopus.self.createCanvas (chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/subtitles_octopus/subtitles-octopus.js:134:26)
    at SubtitlesOctopus.self.init (chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/subtitles_octopus/subtitles-octopus.js:94:14)
    at new SubtitlesOctopus (chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/subtitles_octopus/subtitles-octopus.js:581:10)
    at loadSub (chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/loader.js:44:25)
    at chrome-extension://eddfneakjljnelhpanihljcghnjamfjm/src/loader.js:28:9
```
아마도 유튜브 video 태그가 달라졌기 때문으로 보입니다.

**Comment by nonbanana** [comment]
video tag를 확인해 본 결과 변한것은 없었습니다. 크롬 버전이 올라가며확장프로그램 작동 방법이 달라진 것으로 보입니다.

이전에는 웹페이지가 로드 된 후 확장프로그램이 동작하였지만, 현재는 웹페이지가 로드 되기전에 확장프로그램이 먼저 로드되어 getElements가 정상적으로 수행되지 않은것으로 보입니다. loadSub 시에 getelement를 수행하도록 수정하여 정상적으로 동작하는것을 확인하였습니다.
